apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: message-api
    spec:
      containers:
      - name: message-api
        image: 'message-api:v1'
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: message-api
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ing
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-node
          servicePort: 80
